apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        name: nginx-pod-deloyment
        app: nginx-app
    containers:
        - name: nginx-container
          image: nginx:latest
          ports:
        - containerPort: 80