apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: deeppaakk/mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "******"
        - name: MYSQL_DATABASE
          value: "spring_fullstack"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  type: ClusterIP
